// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqlwbpszR-8RfR_dALQdxuF7wCInlnUHo',
    appId: '1:51220653574:web:297026268097763bcc4587',
    messagingSenderId: '51220653574',
    projectId: 'pabremidi',
    authDomain: 'pabremidi.firebaseapp.com',
    storageBucket: 'pabremidi.firebasestorage.app',
    measurementId: 'G-42H9GEMHDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9OAzN-vnisT5ChDaAoxdj_1Nw-mLkSZs',
    appId: '1:51220653574:android:d80a744854fd3635cc4587',
    messagingSenderId: '51220653574',
    projectId: 'pabremidi',
    storageBucket: 'pabremidi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXgeqgN3KJZr9d2z1CXOk8zbmp-Mqab0Y',
    appId: '1:51220653574:ios:631e0ce6bead886ecc4587',
    messagingSenderId: '51220653574',
    projectId: 'pabremidi',
    storageBucket: 'pabremidi.firebasestorage.app',
    iosBundleId: 'com.example.spacenewsCore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXgeqgN3KJZr9d2z1CXOk8zbmp-Mqab0Y',
    appId: '1:51220653574:ios:631e0ce6bead886ecc4587',
    messagingSenderId: '51220653574',
    projectId: 'pabremidi',
    storageBucket: 'pabremidi.firebasestorage.app',
    iosBundleId: 'com.example.spacenewsCore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqlwbpszR-8RfR_dALQdxuF7wCInlnUHo',
    appId: '1:51220653574:web:041444ee71846c4bcc4587',
    messagingSenderId: '51220653574',
    projectId: 'pabremidi',
    authDomain: 'pabremidi.firebaseapp.com',
    storageBucket: 'pabremidi.firebasestorage.app',
    measurementId: 'G-310KZJPDCS',
  );
}
